// employees data
const Employees = [
    {
      id: 1,
      firstName: 'Marcus',
      lastName: 'Telemachus',
      title: 'Mr',
      team: 'Marketing',
      role: 'Lead',
      email: 'mtel123@gmail.com',
    },
    {
      id: 2,
      firstName: 'Maggie',
      lastName: 'Smith',
      title: 'Ms',
      team: 'Technology',
      role: 'Team member',
      email: 'msmith123@gmail.com',
    },
    {
      id: 3,
      firstName: 'Angelica',
      lastName: 'Ruggle',
      title: 'Ms',
      team: 'Legal',
      role: 'Department head',
      email: 'angieruggle@gmail.com',
    },
    {
      id: 4,
      firstName: 'Arman',
      lastName: 'Ruggieri',
      title: 'Mr',
      team: 'Marketing',
      role: 'team member',
      email: 'armani@gmail.com',
    },
    {
      id: 5,
      firstName: 'Tony',
      lastName: 'Burke',
      title: 'Mr',
      team: 'Legal',
      role: 'team member',
      email: 'tbuk@gmail.com',
    },
    {
      id: 6,
      firstName: 'Avici',
      lastName: 'Prime',
      title: 'Mr',
      team: 'Technology',
      role: 'Senior developer',
      email: 'primovici@gmail.com',
    },
    {
      id: 7,
      firstName: 'Tina',
      lastName: 'Fonda',
      title: 'Miss',
      team: 'Legal',
      role: 'Assistant',
      email: 'tfondue@gmail.com',
    },
    {
      id: 8,
      firstName: 'Ron',
      lastName: 'McDonald',
      title: 'Mr',
      team: 'Marketing',
      role: 'Assistant',
      email: 'bigmick@gmail.com',
    },
    {
      id: 9,
      firstName: 'Angelo',
      lastName: 'Andronichus',
      title: 'Mr',
      team: 'Technology',
      role: 'Chief Technical Officer',
      email: 'andro123@gmail.com',
    },
    {
      id: 10,
      firstName: 'Mason',
      lastName: 'Williams',
      title: 'Mr',
      team: 'Technology',
      role: 'Junior Developer',
      email: 'mwill123@gmail.com',
    }
  ];

  export default Employees;